import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { useCookies } from "./useCookies";
import { decrypt } from "@/lib/decrypt";
import { cookies } from "next/headers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Sick Predection",
  description: "Generated by create next app",
  icons: "",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const decryptSession = async () => {
    const session = cookies().get("session");
    if (session) {
      const payload = await decrypt(session.value);
    }
  };
  decryptSession();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
